/*
 * ndis.h
 *
 * ntddndis.h modified by Benedikt Spranger <b.spranger@pengutronix.de>
 *
 * Thanks to the cygwin development team,
 * espacially to Casper S. Hornstrup <chorns@users.sourceforge.net>
 *
 * THIS SOFTWARE IS NOT COPYRIGHTED
 *
 * This source code is offered for use in the public domain. You may
 * use, modify or distribute it freely.
 */

#ifndef _LINUX_NDIS_H
#define _LINUX_NDIS_H

enum NDIS_DEVICE_POWER_STATE {
	NdisDeviceStateUnspecified = 0,
	NdisDeviceStateD0,
	NdisDeviceStateD1,
	NdisDeviceStateD2,
	NdisDeviceStateD3,
	NdisDeviceStateMaximum
};

struct NDIS_PM_WAKE_UP_CAPABILITIES {
	enum NDIS_DEVICE_POWER_STATE  MinMagicPacketWakeUp;
	enum NDIS_DEVICE_POWER_STATE  MinPatternWakeUp;
	enum NDIS_DEVICE_POWER_STATE  MinLinkChangeWakeUp;
};

struct NDIS_PNP_CAPABILITIES {
	__le32					Flags;
	struct NDIS_PM_WAKE_UP_CAPABILITIES	WakeUpCapabilities;
};

struct NDIS_PM_PACKET_PATTERN {
	__le32	Priority;
	__le32	Reserved;
	__le32	MaskSize;
	__le32	PatternOffset;
	__le32	PatternSize;
	__le32	PatternFlags;
};

#endif /* _LINUX_NDIS_H */

/* Fix for missing NDIS definitions */
#include <linux/rndis.h>
#define NDIS_MEDIA_STATE_CONNECTED    RNDIS_MEDIA_STATE_CONNECTED
#define NDIS_MEDIA_STATE_DISCONNECTED RNDIS_MEDIA_STATE_DISCONNECTED
#define NDIS_MEDIUM_802_3             RNDIS_MEDIUM_802_3
#ifndef REMOTE_NDIS_PACKET_MSG
#define REMOTE_NDIS_PACKET_MSG RNDIS_MSG_PACKET
#endif
#ifndef REMOTE_NDIS_INITIALIZE_MSG
#define REMOTE_NDIS_INITIALIZE_MSG RNDIS_MSG_INIT
#endif
#ifndef REMOTE_NDIS_INITIALIZE_CMPLT
#define REMOTE_NDIS_INITIALIZE_CMPLT RNDIS_MSG_INIT_C
#endif
#ifndef REMOTE_NDIS_QUERY_CMPLT
#define REMOTE_NDIS_QUERY_CMPLT RNDIS_MSG_QUERY_C
#endif
#ifndef REMOTE_NDIS_SET_CMPLT
#define REMOTE_NDIS_SET_CMPLT RNDIS_MSG_SET_C
#endif
#ifndef REMOTE_NDIS_RESET_CMPLT
#define REMOTE_NDIS_RESET_CMPLT RNDIS_MSG_RESET_C
#endif
#ifndef REMOTE_NDIS_KEEPALIVE_CMPLT
#define REMOTE_NDIS_KEEPALIVE_CMPLT RNDIS_MSG_KEEPALIVE_C
#endif
#ifndef REMOTE_NDIS_INDICATE_STATUS_MSG
#define REMOTE_NDIS_INDICATE_STATUS_MSG RNDIS_MSG_INDICATE
#endif
#ifndef REMOTE_NDIS_HALT_MSG
#define REMOTE_NDIS_HALT_MSG RNDIS_MSG_HALT
#endif
#ifndef REMOTE_NDIS_QUERY_MSG
#define REMOTE_NDIS_QUERY_MSG RNDIS_MSG_QUERY
#endif
#ifndef REMOTE_NDIS_SET_MSG
#define REMOTE_NDIS_SET_MSG RNDIS_MSG_SET
#endif
#ifndef REMOTE_NDIS_RESET_MSG
#define REMOTE_NDIS_RESET_MSG RNDIS_MSG_RESET
#endif
#ifndef REMOTE_NDIS_KEEPALIVE_MSG
#define REMOTE_NDIS_KEEPALIVE_MSG RNDIS_MSG_KEEPALIVE
#endif
#ifndef OID_GEN_SUPPORTED_LIST
#define OID_GEN_SUPPORTED_LIST RNDIS_OID_GEN_SUPPORTED_LIST
#endif
#ifndef OID_GEN_HARDWARE_STATUS
#define OID_GEN_HARDWARE_STATUS RNDIS_OID_GEN_HARDWARE_STATUS
#endif
#ifndef OID_GEN_MEDIA_SUPPORTED
#define OID_GEN_MEDIA_SUPPORTED RNDIS_OID_GEN_MEDIA_SUPPORTED
#endif
#ifndef OID_GEN_MEDIA_IN_USE
#define OID_GEN_MEDIA_IN_USE RNDIS_OID_GEN_MEDIA_IN_USE
#endif
#ifndef OID_GEN_MAXIMUM_FRAME_SIZE
#define OID_GEN_MAXIMUM_FRAME_SIZE RNDIS_OID_GEN_MAXIMUM_FRAME_SIZE
#endif
#ifndef OID_GEN_LINK_SPEED
#define OID_GEN_LINK_SPEED RNDIS_OID_GEN_LINK_SPEED
#endif
#ifndef OID_GEN_TRANSMIT_BLOCK_SIZE
#define OID_GEN_TRANSMIT_BLOCK_SIZE RNDIS_OID_GEN_TRANSMIT_BLOCK_SIZE
#endif
#ifndef OID_GEN_RECEIVE_BLOCK_SIZE
#define OID_GEN_RECEIVE_BLOCK_SIZE RNDIS_OID_GEN_RECEIVE_BLOCK_SIZE
#endif
#ifndef OID_GEN_VENDOR_ID
#define OID_GEN_VENDOR_ID RNDIS_OID_GEN_VENDOR_ID
#endif
#ifndef OID_GEN_VENDOR_DESCRIPTION
#define OID_GEN_VENDOR_DESCRIPTION RNDIS_OID_GEN_VENDOR_DESCRIPTION
#endif
#ifndef OID_GEN_VENDOR_DRIVER_VERSION
#define OID_GEN_VENDOR_DRIVER_VERSION RNDIS_OID_GEN_VENDOR_DRIVER_VERSION
#endif
#ifndef OID_GEN_CURRENT_PACKET_FILTER
#define OID_GEN_CURRENT_PACKET_FILTER RNDIS_OID_GEN_CURRENT_PACKET_FILTER
#endif
#ifndef OID_GEN_MAXIMUM_TOTAL_SIZE
#define OID_GEN_MAXIMUM_TOTAL_SIZE RNDIS_OID_GEN_MAXIMUM_TOTAL_SIZE
#endif
#ifndef OID_GEN_MEDIA_CONNECT_STATUS
#define OID_GEN_MEDIA_CONNECT_STATUS RNDIS_OID_GEN_MEDIA_CONNECT_STATUS
#endif
#ifndef OID_GEN_PHYSICAL_MEDIUM
#define OID_GEN_PHYSICAL_MEDIUM RNDIS_OID_GEN_PHYSICAL_MEDIUM
#endif
#ifndef OID_GEN_XMIT_OK
#define OID_GEN_XMIT_OK RNDIS_OID_GEN_XMIT_OK
#endif
#ifndef OID_GEN_RCV_OK
#define OID_GEN_RCV_OK RNDIS_OID_GEN_RCV_OK
#endif
#ifndef OID_GEN_XMIT_ERROR
#define OID_GEN_XMIT_ERROR RNDIS_OID_GEN_XMIT_ERROR
#endif
#ifndef OID_GEN_RCV_ERROR
#define OID_GEN_RCV_ERROR RNDIS_OID_GEN_RCV_ERROR
#endif
#ifndef OID_GEN_RCV_NO_BUFFER
#define OID_GEN_RCV_NO_BUFFER RNDIS_OID_GEN_RCV_NO_BUFFER
#endif
#ifndef OID_802_3_PERMANENT_ADDRESS
#define OID_802_3_PERMANENT_ADDRESS RNDIS_OID_802_3_PERMANENT_ADDRESS
#endif
#ifndef OID_802_3_CURRENT_ADDRESS
#define OID_802_3_CURRENT_ADDRESS RNDIS_OID_802_3_CURRENT_ADDRESS
#endif
#ifndef OID_802_3_MULTICAST_LIST
#define OID_802_3_MULTICAST_LIST RNDIS_OID_802_3_MULTICAST_LIST
#endif
#ifndef OID_802_3_MAC_OPTIONS
#define OID_802_3_MAC_OPTIONS RNDIS_OID_802_3_MAC_OPTIONS
#endif
#ifndef OID_802_3_MAXIMUM_LIST_SIZE
#define OID_802_3_MAXIMUM_LIST_SIZE RNDIS_OID_802_3_MAXIMUM_LIST_SIZE
#endif
#ifndef OID_802_3_RCV_ERROR_ALIGNMENT
#define OID_802_3_RCV_ERROR_ALIGNMENT RNDIS_OID_802_3_RCV_ERROR_ALIGNMENT
#endif
#ifndef OID_802_3_XMIT_ONE_COLLISION
#define OID_802_3_XMIT_ONE_COLLISION RNDIS_OID_802_3_XMIT_ONE_COLLISION
#endif
#ifndef OID_802_3_XMIT_MORE_COLLISIONS
#define OID_802_3_XMIT_MORE_COLLISIONS RNDIS_OID_802_3_XMIT_MORE_COLLISIONS
#endif
#ifndef OID_GEN_MAC_OPTIONS
#define OID_GEN_MAC_OPTIONS RNDIS_OID_GEN_MAC_OPTIONS
#endif
#ifndef NDIS_MAC_OPTION_RECEIVE_SERIALIZED
#define NDIS_MAC_OPTION_RECEIVE_SERIALIZED RNDIS_MAC_OPTION_RECEIVE_SERIALIZED
#endif
#ifndef NDIS_MAC_OPTION_FULL_DUPLEX
#define NDIS_MAC_OPTION_FULL_DUPLEX RNDIS_MAC_OPTION_FULL_DUPLEX
#endif
